I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 196, in script
    if panic:
  File "game/script.rpy", line 196, in <module>
    if panic:
NameError: name 'panic' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 196, in script
    if panic:
  File "C:\Users\Greshnick\Desktop\renpy-8.2.0-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Greshnick\Desktop\renpy-8.2.0-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Greshnick\Desktop\renpy-8.2.0-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 196, in <module>
    if panic:
NameError: name 'panic' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
VisualNovelRenPy 1.0
Wed Feb 14 11:13:05 2024
